const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1400,height:1000}});
  const errs=[]; p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + __dirname + '/t_view.html'); await p.waitForTimeout(300);
  await p.evaluate(async()=>{ loadStandardCoa(); await new Promise(r=>setTimeout(r,300));
    const je=(dt,dr,cr,amt,party)=>addRec('documents',{type:'journalEntry',typeLabel:'สมุดรายวันทั่วไป',group:'other',party,date:dt,docNo:'J-'+party,items:[{account:dr,debit:amt,credit:0},{account:cr,debit:0,credit:amt}],total:amt,createdAt:Date.now()});
    await je('2026-09-01','1120','3110',10000,'ทุน'); await je('2026-09-10','5290','1120',1500,'ค่าไฟ'); await je('2026-09-20','1120','4110',3000,'ขาย'); });
  await p.evaluate(()=>go('accounting','reconcile')); await p.waitForTimeout(300);
  await p.selectOption('#recAcc','1120'); await p.waitForTimeout(100);
  await p.click('[data-stmtimp]'); await p.waitForTimeout(100);
  const csv='ธนาคารกสิกรไทย รายการเดินบัญชี\nวันที่,รายการ,ถอน,ฝาก,ยอดคงเหลือ\n01/09/2026,ฝากเงินทุน,,10000,10000\n11/09/2026,ชำระค่าไฟ,1500,,8500\n21/09/2026,รับโอน,,3000,11500\n30/09/2026,ค่าธรรมเนียม,50,,11450\n';
  await p.setInputFiles('#stFile',{name:'st.csv',mimeType:'text/csv',buffer:Buffer.from(csv)}); await p.waitForTimeout(300);
  console.log(await p.evaluate(()=>byId('stPrev').innerText));
  await p.click('#modalFoot >> text=นำเข้าและจับคู่'); await p.waitForTimeout(200);
  console.log(await p.evaluate(()=>[byId('recEnd').value, byId('recEndBal').value]));
  await p.click('#recStart'); await p.waitForTimeout(300);
  console.log(await p.evaluate(()=>JSON.stringify([rec.match, reconCalc()])));
  await p.selectOption('[data-stacc="3"]','5290'); await p.waitForTimeout(500);
  await p.screenshot({path:'stm.png'});
  console.log(await p.evaluate(()=>JSON.stringify(reconCalc())), errs); await b.close();
})();
