const { chromium } = require('playwright');
(async () => { const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1300,height:800}}); const errs=[]; p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + __dirname + '/t_view.html'); await p.waitForTimeout(300); await p.evaluate(()=>loadStandardCoa()); await p.waitForTimeout(300);
  await p.evaluate(()=>go('project')); await p.waitForTimeout(200);
  await p.click('[data-dimadd]'); await p.fill('#dmName','ปรับปรุงสาขาเชียงใหม่'); await p.fill('#dmDesc','งานตกแต่งภายใน'); await p.click('#modalFoot >> text=บันทึก'); await p.waitForTimeout(300);
  await p.evaluate(()=>go('project','dept')); await p.waitForTimeout(200);
  await p.click('[data-dimadd]'); await p.fill('#dmName','ฝ่ายขาย'); await p.click('#modalFoot >> text=บันทึก'); await p.waitForTimeout(300);
  await p.evaluate(()=>openDocForm('invoice')); await p.waitForTimeout(200);
  await p.fill('#f_party','ลูกค้า A'); await p.selectOption('#f_project',{index:1}); await p.selectOption('#f_dept',{index:1});
  await p.evaluate(()=>{ form.items=[{name:'x',qty:1,price:1000}]; }); await p.click('#modalFoot >> text=บันทึก'); await p.waitForTimeout(300);
  await p.evaluate(()=>go('project','list')); await p.waitForTimeout(200); await p.screenshot({path:'proj.png'});
  console.log(await p.evaluate(()=>byId('pageData').innerText), await p.evaluate(()=>{go('project','dept'); return byId('pageData').innerText;}), errs); await b.close(); })();
