const { chromium } = require('playwright');
(async () => { const b = await chromium.launch(); const ctx = await b.newContext({viewport:{width:1300,height:950}});
  await ctx.addInitScript(()=>{ const s=async()=>({text:''}); s.limits=async()=>({maxPromptBytes:1e6,images:{maxCount:5,maxInputBytes:5e6,mediaTypes:['image/jpeg']}}); s.json=async(p,o)=>{ window.__imgs=o.images&&o.images.length; await new Promise(r=>setTimeout(r,200)); return {vendorName:'บริษัท น้ำมันตัวอย่าง จำกัด',vendorTaxId:'0105550000023',docNo:'RC-88821',date:'2026-09-20',items:[{name:'น้ำมันดีเซล',qty:30,price:32.5}],vatMode:'inclusive',total:975,whtRate:0,paid:true,category:'ค่าน้ำมัน'}; }; window.claude={use:async n=> n==='sample'?s:null}; });
  const p = await ctx.newPage(); const errs=[]; p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + __dirname + '/t_view.html'); await p.waitForTimeout(500); await p.evaluate(()=>loadStandardCoa()); await p.waitForTimeout(300);
  await p.evaluate(()=>go('accounting','receiptCapture')); await p.waitForTimeout(200);
  await p.setInputFiles('#ocrFile','/tmp/rc.jpg'); await p.waitForTimeout(1200);
  await p.screenshot({path:'ocr.png'});
  await p.click('[data-ocrsave="0"]'); await p.waitForTimeout(600);
  console.log(await p.evaluate(()=>[window.__imgs, JSON.stringify(STORE.documents.map(d=>[d.type,d.docNo,d.party,d.subtotal,d.vat,d.total,d.extra.supInvNo,d.extra.account])), STORE.contacts.map(c=>c.name+' '+c.taxId)]), errs); await b.close(); })();
