const { chromium } = require('playwright');
(async () => { const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1300,height:900}}); const errs=[]; p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + __dirname + '/t_view.html'); await p.waitForTimeout(300);
  await p.evaluate(async()=>{ loadStandardCoa(); await new Promise(r=>setTimeout(r,300));
    await addRec('documents',{type:'journalEntry',typeLabel:'JE',group:'other',party:'ขาย',date:'2026-01-10',docNo:'J1',items:[{account:'1120',debit:500,credit:0},{account:'4110',debit:0,credit:500}],total:500,createdAt:1}); });
  await p.evaluate(()=>go('accounting','reconcile')); await p.waitForTimeout(200); await p.selectOption('#recAcc','1120');
  await p.click('[data-stmtimp]'); await p.setInputFiles('#stFile',{name:'s.csv',mimeType:'text/csv',buffer:Buffer.from('วันที่,รายการ,ถอน,ฝาก,ยอดคงเหลือ\n10/01/2026,รับเงิน,,500,1000500\n')}); await p.waitForTimeout(300);
  await p.click('#modalFoot >> text=นำเข้าและจับคู่'); await p.waitForTimeout(300);
  console.log('beg', await p.evaluate(()=>byId('recBeg').value));
  await p.click('#recStart'); await p.waitForTimeout(300);
  console.log(await p.evaluate(()=>JSON.stringify(reconCalc())), errs); await b.close(); })();
