const { chromium } = require('playwright');
(async () => { const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1300,height:900}}); const errs=[]; p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + __dirname + '/t_view.html'); await p.waitForTimeout(300);
  const r = await p.evaluate(async()=>{ const mk=async()=>{ const no=nextDocNo('invoice','2026-09-10'); await addRec('documents',{type:'invoice',typeLabel:'ใบแจ้งหนี้',group:'customer',party:'A',date:'2026-09-10',docNo:no,items:[{name:'x',qty:1,price:100}],vatMode:'none',subtotal:100,vat:0,total:100,net:100,extra:{},status:'unpaid',createdAt:Date.now()}); return no; };
    const a=await mk(), b2=await mk(), c=await mk();
    await delRec('documents', STORE.documents.find(d=>d.docNo===b2)._id);
    const d=await mk();
    return [a,b2,c,d]; });
  console.log('numbers', r);
  await p.evaluate(()=>openDocDetail(STORE.documents.find(d=>d.docNo.endsWith('-001'))._id)); await p.waitForTimeout(200);
  await p.click('#modalFoot >> text=ยกเลิกเอกสาร'); await p.fill('#voidReason','ออกผิด'); await p.click('#modalFoot >> text=ยืนยันยกเลิกเอกสาร'); await p.waitForTimeout(300);
  console.log(await p.evaluate(()=>{ const v=STORE.documents.find(d=>d.docNo.endsWith('-001')); return [v.voided, docStatus(v), postingsOf(v).length, nextDocNo('invoice','2026-09-10'), (accountBalances()['1130']||{}).dr]; }));
  await p.evaluate(()=>openDocDetail(STORE.documents.find(d=>d.docNo.endsWith('-001'))._id)); await p.waitForTimeout(200); await p.screenshot({path:'void.png'});
  console.log(errs); await b.close(); })();
